### ISSUE TITLE
Ubuntu Bionic stemcell - Increased CPU load

### ISSUE THREAD

**Issue by brunograz** [cloudfoundry/pxc-release#17] opened 2021-10-12 15:26 UTC
Thank you for submitting an issue.

# Bug Report Info
## Currently:
What is the current broken behavior?

The issue manifested when we migrated from Xenial to Bionic. We noticed an increase in the average load of the galera VMs and cpu utilization almost doubles up compared to the release running on xenial. When the system is stressed the amount of slow queries is increased significantly.

![image](https://user-images.githubusercontent.com/8091247/136981207-577f3280-7cdd-4575-b2b0-c43ffe2f17a0.png)

We are using this release in a testing environment for Cloud Foundry which is the only release consuming the database. It is also worth noting that the load expected from this environment is quite low as it is not often used.

As you can see in the image above, the red arrow point to when we changed the underlying OS to bionic and the peaks in the load are due to running tests in the platform. Reverting it back to xenial brings down the cpu utilization again.
Due to the increase of the load, many API calls take much longer to complete impacting the management plane of the platform.

Given that the manifests are still pointing to xenial, I am opening this issue to track its development towards bionic and when should we expect it as an official release.

## Deployment Context:
Please provide relevant details about your deployment. That might include:
* Are you using cf-mysql-release with a service broker? -  No
* How many nodes and proxies are deployed? - 3 Galera nodes and 3 proxies
* Release version - 0.37.0
* Stemcell - Bionic v1.25

**Comment by abg** [comment] 2022-09-27 12:43
Is this issue still a problem in 2022? We looked at this briefly and were unable to reproduce the problem.

I am going to close this issue, but feel free to reopen if this is a continued pain point.

**Closed by abg** 2022-09-27 12:43 UTC
Labels: unscheduled
